Add return and where clause
birch-wood/tanK pull request #29
Opened 2020-02-17 09:46 UTC by martinemdal

Added a missing return clause rather than allowing for it to be implicit in any query context. Also added a naive where clause with a greater than function.

2020-02-17 09:48 UTC, martinemdal commented on src/main/kotlin/net/emdal/tank/clause/WhereClause.kt
> +  infix fun Property.greaterThan(value: Any) = WhereClause(
Should greater than be allowed for all `Property`s. Might not make sense for string or other types of properties. This should be a function of `IntProperty`.

2020-02-23 10:05 UTC, martinemdal commented on src/main/kotlin/net/emdal/tank/clause/ReturnClause.kt
> +  override var aliases: Map<String, List<Entity>> = emptyMap()
Aliases are not in use anywhere. The type inference between the string alias and the entity types do no carry on between clauses which means this is most likely useless to keep adding to the clauses. I think we should remove the `aliases` field from Clause and rather add it back in if needed for something in the future.

2020-02-23 10:13 UTC, martinemdal commented
Also removed the aliases map from Clauses as it is not currently being used for anything.

2020-02-24 07:51 UTC, kollstrom requested changes

2020-02-24 07:51 UTC, kollstrom commented on src/main/kotlin/net/emdal/tank/clause/WhereClause.kt
> +  override var query: List<String> = listOf("WHERE ")
Should this be a part of the constructor

2020-05-20 06:02 UTC, kollstrom approved these changes

2020-06-19 10:21 UTC, kollstrom commented
@martinemdal Should we try to get this merged soon?

2020-06-19 13:25 UTC, merged